const graph = () => `https://graph.facebook.com/${process.env.META_GRAPH_VERSION ?? "v21.0"}`;
export async function sendTextMessage(phone: string, body: string) { const id=process.env.META_PHONE_NUMBER_ID, token=process.env.META_ACCESS_TOKEN; if(!id||!token) throw new Error("META_PHONE_NUMBER_ID o META_ACCESS_TOKEN no configurados"); const res=await fetch(`${graph()}/${id}/messages`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",recipient_type:"individual",to:phone,type:"text",text:{preview_url:false,body}})}); if(!res.ok) throw new Error(`Graph API ${res.status}: ${await res.text()}`); const json=await res.json(); const waId=json?.messages?.[0]?.id; if(!waId) throw new Error(`Respuesta Graph sin id: ${JSON.stringify(json)}`); return {wa_message_id:waId}; }
export async function sendImageMessage(phone: string, imageUrl: string, caption?: string) { const id=process.env.META_PHONE_NUMBER_ID, token=process.env.META_ACCESS_TOKEN; if(!id||!token) throw new Error("META_PHONE_NUMBER_ID o META_ACCESS_TOKEN no configurados"); const res=await fetch(`${graph()}/${id}/messages`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",recipient_type:"individual",to:phone,type:"image",image:{link:imageUrl,caption}})}); if(!res.ok) throw new Error(`Graph API ${res.status}: ${await res.text()}`); const json=await res.json(); const waId=json?.messages?.[0]?.id; if(!waId) throw new Error(`Respuesta Graph sin id: ${JSON.stringify(json)}`); return {wa_message_id:waId}; }
export async function sendImageBuffer(phone: string, bytes: Buffer, caption?: string) {
  const id=process.env.META_PHONE_NUMBER_ID, token=process.env.META_ACCESS_TOKEN;
  if(!id||!token) throw new Error("META_PHONE_NUMBER_ID o META_ACCESS_TOKEN no configurados");
  const form=new FormData(); form.set("messaging_product","whatsapp"); form.set("file",new Blob([new Uint8Array(bytes)],{type:"image/jpeg"}),"catalogo.jpg");
  const upload=await fetch(`${graph()}/${id}/media`,{method:"POST",headers:{Authorization:`Bearer ${token}`},body:form});
  if(!upload.ok) throw new Error(`Graph media ${upload.status}: ${await upload.text()}`);
  const media=await upload.json() as {id?:string};
  if(!media.id) throw new Error(`Graph media sin id: ${JSON.stringify(media)}`);
  const res=await fetch(`${graph()}/${id}/messages`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",recipient_type:"individual",to:phone,type:"image",image:{id:media.id,caption}})});
  if(!res.ok) throw new Error(`Graph API ${res.status}: ${await res.text()}`);
  const json=await res.json(); const waId=json?.messages?.[0]?.id;
  if(!waId) throw new Error(`Respuesta Graph sin id: ${JSON.stringify(json)}`);
  return {wa_message_id:waId};
}
export async function downloadWhatsAppMedia(mediaId: string) { const token=process.env.META_ACCESS_TOKEN; if(!token) throw new Error("META_ACCESS_TOKEN no configurado"); const metadata=await fetch(`${graph()}/${mediaId}`,{headers:{Authorization:`Bearer ${token}`}}); if(!metadata.ok) throw new Error(`Graph API ${metadata.status}: ${await metadata.text()}`); const info=await metadata.json() as {url?:string;mime_type?:string}; if(!info.url) throw new Error("Graph API no devolvió URL del archivo"); const file=await fetch(info.url,{headers:{Authorization:`Bearer ${token}`}}); if(!file.ok) throw new Error(`No se pudo descargar el comprobante: ${file.status}`); return {bytes:await file.arrayBuffer(),mimeType:info.mime_type??file.headers.get("content-type")??"image/jpeg"}; }
export async function getPhoneNumberInfo() { const id=process.env.META_PHONE_NUMBER_ID, token=process.env.META_ACCESS_TOKEN; if(!id||!token) throw new Error("Credenciales Meta incompletas"); const res=await fetch(`${graph()}/${id}?fields=display_phone_number,verified_name,quality_rating`,{headers:{Authorization:`Bearer ${token}`}}); if(!res.ok) throw new Error(`Graph ${res.status}: ${await res.text()}`); return await res.json() as {display_phone_number:string;verified_name:string;quality_rating:string}; }
