create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  phone text not null unique, name text,
  mode text not null default 'AI' check (mode in ('AI', 'HUMAN')),
  last_message_at bigint,
  created_at bigint not null default extract(epoch from now())::bigint
);
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'human')),
  content text not null, wa_message_id text unique,
  created_at bigint not null default extract(epoch from now())::bigint
);
create index if not exists idx_messages_conv on public.messages (conversation_id, created_at, id);
create index if not exists idx_conversations_last_message on public.conversations (last_message_at desc, id desc);
create table if not exists public.processed_webhook_messages (
  wa_message_id text primary key,
  processed_at bigint not null default extract(epoch from now())::bigint
);
create or replace view public.conversation_summaries with (security_invoker = true) as
select c.*, last_message.content as last_message_preview
from public.conversations c
left join lateral (
  select content from public.messages m where m.conversation_id = c.id
  order by m.created_at desc, m.id desc limit 1
) last_message on true;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.processed_webhook_messages enable row level security;
-- The server uses SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS. Never expose it to browser code.
