create table if not exists public.whatsapp_orders (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  numero_pedido text not null unique,
  pago_id text not null,
  estado text not null default 'PENDING_PAYMENT',
  created_at bigint not null default extract(epoch from now())::bigint
);
create index if not exists idx_whatsapp_orders_pending on public.whatsapp_orders (conversation_id, estado, id desc);
alter table public.whatsapp_orders enable row level security;
