const baseUrl = () => (process.env.CENTRAL_API_URL ?? "https://control-ventas-azure.vercel.app/api").replace(/\/$/, "");
function key() { const value=process.env.CENTRAL_WHATSAPP_SERVICE_KEY; if(!value) throw new Error("CENTRAL_WHATSAPP_SERVICE_KEY no configurada"); return value; }
async function request(path:string, init:RequestInit={}) { const headers=new Headers(init.headers); headers.set("Authorization",`Bearer ${key()}`); if(init.body && !headers.has("Content-Type") && !(init.body instanceof FormData)) headers.set("Content-Type","application/json"); const response=await fetch(`${baseUrl()}${path}`,{...init,headers,cache:"no-store"}); const raw=await response.text(); let data:unknown; try { data=raw?JSON.parse(raw):{}; } catch { data={message:raw}; } if(!response.ok) throw new Error(`Sistema central ${response.status}: ${typeof data==="object"&&data&&"message" in data?String(data.message):raw}`); return data as any; }
export async function searchCatalog(filters:Record<string,unknown>) { const params=new URLSearchParams({soloDisponible:"true",limit:"10"}); for(const [key,value] of Object.entries(filters)) if(typeof value==="string"&&value.trim()) params.set(key,value.trim()); const result=await request(`/productos/publicos?${params}`); return Array.isArray(result)?result:result.data??[]; }
export async function productDetail(productId:string) { return request(`/productos/publicos/${encodeURIComponent(productId)}`); }
export async function deliveryOptions() { return request("/delivery-options"); }
export async function createWhatsAppOrder(body:unknown) { return request("/integrations/whatsapp/orders",{method:"POST",body:JSON.stringify(body)}); }
export async function orderStatus(number:string, phone:string) { return request(`/integrations/whatsapp/orders/${encodeURIComponent(number)}?phone=${encodeURIComponent(phone)}`); }
export async function uploadPaymentProof(paymentId:string, bytes:ArrayBuffer, mimeType:string) { const form=new FormData(); form.set("file",new Blob([bytes],{type:mimeType}),"comprobante.jpg"); return request(`/integrations/whatsapp/payments/${encodeURIComponent(paymentId)}/proof`,{method:"POST",body:form}); }
