import OpenAI from "openai";
import { SYSTEM_PROMPT } from "./system-prompt";
import { createWhatsAppOrder, deliveryOptions, orderStatus, productDetail, searchCatalog, uploadPaymentProof } from "./fit-andes-api";
import { latestPendingWhatsAppOrder, saveWhatsAppOrder, setMode, setWhatsAppOrderStatus } from "./db";
import { downloadWhatsAppMedia, sendImageMessage, sendTextMessage } from "./meta/client";

type Context = { phone:string; name:string|null; conversationId:number; messageId:string };
const ownerPhone="59167113105";
const tools:any[]=[
  {type:"function",function:{name:"buscar_productos",description:"Busca chompas o poleras disponibles por texto, categoría, color o talla. Úsala antes de asegurar disponibilidad o precio.",parameters:{type:"object",properties:{q:{type:"string"},categoria:{type:"string"},color:{type:"string"},talla:{type:"string"}},additionalProperties:false}}},
  {type:"function",function:{name:"ver_opciones_entrega",description:"Obtiene puntos, horarios y agencias válidas para ofrecer una entrega.",parameters:{type:"object",properties:{},additionalProperties:false}}},
  {type:"function",function:{name:"enviar_foto_producto",description:"Envía al cliente la foto de una variante que ya consultaste.",parameters:{type:"object",properties:{productoId:{type:"string"},varianteId:{type:"string"}},required:["productoId","varianteId"],additionalProperties:false}}},
  {type:"function",function:{name:"crear_pedido",description:"Crea y reserva un pedido solo cuando el cliente ya confirmó producto, variante, cantidad, datos de entrega y pago QR.",parameters:{type:"object",properties:{customerName:{type:"string"},items:{type:"array",items:{type:"object",properties:{productoId:{type:"string"},varianteId:{type:"string"},cantidad:{type:"integer",minimum:1}},required:["productoId","varianteId","cantidad"],additionalProperties:false}},delivery:{type:"object",properties:{method:{type:"string",enum:["PICKUP_POINT","SHIPPING_NATIONAL"]},scheduledFor:{type:"string"},pickupPointId:{type:"string"},pickupScheduleId:{type:"string"},department:{type:"string"},city:{type:"string"},shippingCompanyId:{type:"string"},branch:{type:"string"},recipientName:{type:"string"},recipientCi:{type:"string"},phone:{type:"string"}},required:["method","scheduledFor","recipientName","phone"],additionalProperties:false},notes:{type:"string"}},required:["items","delivery"],additionalProperties:false}}},
  {type:"function",function:{name:"consultar_pedido",description:"Consulta el estado de un pedido Fit Andes del cliente actual.",parameters:{type:"object",properties:{numeroPedido:{type:"string"}},required:["numeroPedido"],additionalProperties:false}}},
  {type:"function",function:{name:"derivar_humano",description:"Deriva la conversación a un asesor humano si el cliente lo solicita o hay una excepción.",parameters:{type:"object",properties:{motivo:{type:"string"}},required:["motivo"],additionalProperties:false}}}
];
function client() { const key=process.env.OPENROUTER_API_KEY; if(!key) throw new Error("OPENROUTER_API_KEY no configurada"); return new OpenAI({apiKey:key,baseURL:"https://openrouter.ai/api/v1"}); }
function parse(value:string|undefined) { try{return value?JSON.parse(value):{};}catch{return {}; } }
function compactCatalog(products:any[]) { return products.map((p)=>({id:p._id,nombre:p.nombre,modelo:p.modelo,categoria:p.categoria,precioVenta:p.precioVenta,variantes:(p.variantes??[]).filter((v:any)=>(v.stockDisponible??(v.stock-v.stockReservado))>0).map((v:any)=>({id:v.varianteId,color:v.color,colorSecundario:v.colorSecundario,talla:v.talla,stockDisponible:v.stockDisponible??(v.stock-v.stockReservado),descripcion:v.descripcion,imagen:v.imagen??v.imagenes?.[0]}))})); }
async function notifyOwner(text:string) { try { await sendTextMessage(ownerPhone,text); } catch(error) { console.error("[fit-andes] no se pudo notificar al asesor:",error); } }
async function runTool(name:string,args:any,ctx:Context) {
  if(name==="buscar_productos") return compactCatalog(await searchCatalog(args));
  if(name==="ver_opciones_entrega") return await deliveryOptions();
  if(name==="enviar_foto_producto") { const product=await productDetail(args.productoId); const item=product.data??product; const variant=(item.variantes??[]).find((v:any)=>v.varianteId===args.varianteId); const image=variant?.imagen??variant?.imagenes?.[0]; if(!image) return {ok:false,message:"No hay imagen disponible para esa variante."}; await sendImageMessage(ctx.phone,image,`${item.nombre} · ${variant.color}${variant.talla?` · Talla ${variant.talla}`:""}`); return {ok:true,message:"Foto enviada al cliente."}; }
  if(name==="crear_pedido") { const body={idempotencyKey:ctx.messageId,customer:{phone:ctx.phone,name:args.customerName??ctx.name??undefined},items:args.items,paymentMethod:"QR",delivery:{...args.delivery,phone:args.delivery.phone||ctx.phone,recipientName:args.delivery.recipientName||args.customerName||ctx.name||"Cliente"},notes:args.notes}; const order=await createWhatsAppOrder(body); await saveWhatsAppOrder(ctx.conversationId,{numeroPedido:order.numeroPedido,pagoId:order.pagoId,estado:order.estado}); if(order.paymentInstructions?.qrImageUrl) await sendImageMessage(ctx.phone,order.paymentInstructions.qrImageUrl,`QR BancoSol · Pedido ${order.numeroPedido} · Total Bs ${order.total}`); if(order.notification?.text) await notifyOwner(order.notification.text); return {numeroPedido:order.numeroPedido,total:order.total,costoEnvio:order.costoEnvio,estado:order.estado,vencimientoReserva:order.vencimientoReserva,qrEnviado:Boolean(order.paymentInstructions?.qrImageUrl)}; }
  if(name==="consultar_pedido") return await orderStatus(args.numeroPedido,ctx.phone);
  if(name==="derivar_humano") { await setMode(ctx.conversationId,"HUMAN"); await notifyOwner(`Atención humana solicitada por ${ctx.name??ctx.phone} (${ctx.phone}). Motivo: ${args.motivo}`); return {ok:true,message:"Conversación derivada al asesor humano."}; }
  return {ok:false,message:"Herramienta desconocida"};
}

export async function respondToFitAndes(history:{role:string;content:string}[],ctx:Context) {
  const messages:any[]=[{role:"system",content:SYSTEM_PROMPT},...history.map((m)=>({role:m.role==="user"?"user":"assistant",content:m.content}))];
  for(let round=0;round<6;round++) { const completion=await client().chat.completions.create({model:process.env.OPENROUTER_MODEL??"openai/gpt-4o-mini",messages,tools,tool_choice:"auto"}); const message:any=completion.choices[0]?.message; if(!message) throw new Error("OpenRouter no devolvió una respuesta"); messages.push(message); if(!message.tool_calls?.length) return message.content?.trim()||"Déjame derivarte con un asesor humano."; for(const call of message.tool_calls) { let result:unknown; try { result=await runTool(call.function.name,parse(call.function.arguments),ctx); } catch(error) { result={ok:false,message:error instanceof Error?error.message:"No se pudo consultar el sistema"}; } messages.push({role:"tool",tool_call_id:call.id,content:JSON.stringify(result)}); } }
  return "Estoy verificando los detalles con el sistema. Un asesor te ayudará enseguida.";
}

export async function registerPaymentProof(ctx:Context,mediaId:string) { const order=await latestPendingWhatsAppOrder(ctx.conversationId); if(!order) return "No encuentro un pedido pendiente de pago en este chat. Envíame primero el número de pedido o pide ayuda a un asesor."; const media=await downloadWhatsAppMedia(mediaId); const result=await uploadPaymentProof(order.pago_id,media.bytes,media.mimeType); await setWhatsAppOrderStatus(order.numero_pedido,"PROOF_UPLOADED"); if(result.notification?.text) await notifyOwner(result.notification.text); return `Listo, registramos tu comprobante del pedido ${order.numero_pedido}. Un asesor validará el pago y te confirmará por este medio.`; }
